# -*- coding: utf-8 -*-
"""get_prime_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLtn0ecv0t3fnnmnleMpJHcWXVZ5zcQ5
"""

#prime nubmer 1000000
import numpy
t=0
for n in range(2,1000001):
    result = numpy.sqrt(n)
    if result < 2:
        print(n, 'is prime nubmer')
    else:
        counts = 0
        for x in range(2,int(numpy.sqrt(n))+1):
            r = n/x
            if r.is_integer() is True:
                counts +=1
                break
        if counts == 0:        
            print(n,'is prime number')
            t +=1
print('Total:', t)